puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Stephen Lloyd"
puts "Alex Peattie"
puts "Ruben Kostucki"
puts "Mihai Cojocar"
puts "Nicole Tredway"
puts "Yvette Cook"
puts "Ella Schofield"
puts "Victoria Barr"
puts "Bernard Mordan"
puts "Elena Garrone"
puts "Stephen Giles"
puts "Ana Nogal"
puts "Craig Horsborough"
puts "Tim Scully"
puts "Fadie H"
puts "Mala"
puts "Z Rasool"
puts "Galicians"
puts "Danjo Cutler"
puts "Camilla van Klinken"
puts "Sandrine"
puts "James Carter"
puts "SL Stevens"
puts "Schlap"
puts "Andrew Hercules"
puts "Karin Nielsen"
puts "Andrew Snead"
puts "Rachel Nolan"
puts "Anna Schechter"
puts "Alex Fakhri"
puts "Andrew Harrison"
print "Overall, we have"
print 30
puts " great students"

